### ISSUE TITLE
Quadruple reporting when using WSL

### ISSUE THREAD

**Issue by whaaaley** [gavoja/simple-watcher#3]
I've been using this package on an off for a while. Recently I've been trying to clean up some dev server code since I've moved from macOS to WSL. Probably due to a number of issues, watching a Windows drive through the `/mnt` dir from WSL causes 4 change events on every file update.

In my own project I'm going to try to copy the deboucing over to the Linux function. I just thought I'd post there here in case you want to support WSL. I hope one day WSL figures out a better system for reporting file changes but in the meantime this is how it is.

**Comment by gavoja** [comment]
I'll look into it.

**Comment by gavoja** [comment]
Fixed.
